# Generated by Django 5.2.3 on 2026-01-15 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="검색어")),
                (
                    "search_mode",
                    models.CharField(
                        choices=[
                            ("basic", "기본"),
                            ("llm", "LLM"),
                            ("shopping_research", "쇼핑 리서치"),
                        ],
                        help_text="기본/LLM/쇼핑 리서치",
                        max_length=20,
                        verbose_name="검색 모드",
                    ),
                ),
                ("searched_at", models.DateTimeField(verbose_name="검색 일시")),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호(가격변동 값 API 사용시 필요)",
                        max_length=15,
                        verbose_name="상품번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Search",
                "verbose_name_plural": "Searches",
                "db_table": "search",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentViewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적 삭제 플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_views",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent View",
                "verbose_name_plural": "Recent Views",
                "db_table": "recent_views",
                "ordering": ["-updated_at"],
            },
        ),
    ]
