# Generated by Django 5.0.14 on 2026-01-18 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="기록일시"
                    ),
                ),
                (
                    "lowest_price",
                    models.IntegerField(blank=True, null=True, verbose_name="최저가"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "db_table": "price_histories",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "recorded_at"],
                        name="price_histo_product_b2c64f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PricePredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_price", models.IntegerField(verbose_name="목표가")),
                ("predicted_price", models.IntegerField(verbose_name="예측가격")),
                ("prediction_date", models.DateTimeField(verbose_name="예측일자")),
                (
                    "confidence_score",
                    models.FloatField(blank=True, null=True, verbose_name="신뢰도"),
                ),
                (
                    "purchase_suitability_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="구매적합도점수"
                    ),
                ),
                (
                    "purchase_guide_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="구매가이드메시지"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="활성화여부"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_predictions",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_predictions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Prediction",
                "verbose_name_plural": "Price Predictions",
                "db_table": "price_predictions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "prediction_date"],
                        name="price_predi_product_c80932_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="price_predi_user_id_0a8c79_idx",
                    ),
                ],
            },
        ),
    ]
