# Generated by Django 5.2.3 on 2026-01-15 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "db_table": "purchase",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mall_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="리뷰 쇼핑몰명",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="리뷰 작성자"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="내용"),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="평점"),
                ),
                (
                    "ai_review_summary",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI 리뷰 요약"
                    ),
                ),
                (
                    "external_review_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="외부 쇼핑몰 리뷰 총합"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="수량")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "db_table": "storages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[("charge", "충전"), ("payment", "결제")],
                        help_text="충전/결제",
                        max_length=20,
                        null=True,
                        verbose_name="유형",
                    ),
                ),
                (
                    "token_change",
                    models.IntegerField(
                        blank=True,
                        help_text="충전은+/결제는-",
                        null=True,
                        verbose_name="변동된 토큰양",
                    ),
                ),
                (
                    "token_balance_after",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="변동후토큰양"
                    ),
                ),
                (
                    "token_owner_id",
                    models.IntegerField(
                        blank=True,
                        help_text="결제 토큰 조회목적",
                        null=True,
                        verbose_name="토큰 주인",
                    ),
                ),
                (
                    "transaction_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="거래일시"
                    ),
                ),
                (
                    "danawa_product_id",
                    models.CharField(
                        help_text="다나와 상품 고유 번호(가격변동 값 API 사용시 필요)",
                        max_length=15,
                        verbose_name="상품번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
            ],
            options={
                "verbose_name": "Token History",
                "verbose_name_plural": "Token Histories",
                "db_table": "token_histories",
                "ordering": ["-transaction_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, null=True, verbose_name="수량"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="논리적삭제플래그"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="products.productmodel",
                        verbose_name="상품번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Item",
                "verbose_name_plural": "Purchase Items",
                "db_table": "purchase_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
