# Generated by Django 5.2.3 on 2026-01-15 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="purchaseitemmodel",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.purchasemodel",
                verbose_name="구매번호",
            ),
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.productmodel",
                verbose_name="상품번호",
            ),
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="storagemodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_items",
                to="products.productmodel",
                verbose_name="상품번호",
            ),
        ),
        migrations.AddField(
            model_name="storagemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddField(
            model_name="tokenhistorymodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="회원번호",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmodel",
            index=models.Index(
                fields=["product", "created_at"], name="reviews_product_9e5afb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmodel",
            index=models.Index(
                fields=["user", "created_at"], name="reviews_user_id_fc2a09_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storagemodel",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="tokenhistorymodel",
            index=models.Index(
                fields=["user", "transaction_at"], name="token_histo_user_id_39bdc2_idx"
            ),
        ),
    ]
