# Generated by Django 5.2.3 on 2026-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewmodel",
            name="review_images",
            field=models.JSONField(
                blank=True, default=list, verbose_name="리뷰 이미지 URL 목록"
            ),
        ),
    ]
